name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Forrmat & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: BiomeJS | Setup
        uses: biomejs/setup-biome@v2
      
      - name: BiomeJS | Forrmat & Lint
        run: biome ci .

  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: Docker | Setup
        uses: docker/setup-buildx-action@v3

      - name: Node | Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Node | Install
        run: |
            npm install

      - name: Node | Test
        run: |
            npm test

      - name: Docker | Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: Kasheba/be-analytics-api:latest